/**
 * Mermaid Syntax Fixer
 * Fixes common Mermaid syntax errors generated by LLMs
 */

/**
 * Fix common Mermaid syntax errors
 */
export function fixMermaidSyntax(code: string): string {
  let fixed = code;

  // Fix 1: Multiple classes on same line (e.g., "class A,B,C;")
  // Split into separate class definitions
  fixed = fixMultipleClassesOnLine(fixed);

  // Fix 2: Missing newlines between classDef and class statements
  fixed = fixClassDefSpacing(fixed);

  // Fix 3: Invalid class definitions with extra semicolons
  fixed = fixClassSemicolons(fixed);

  // Fix 4: Fix common flowchart syntax issues
  fixed = fixFlowchartSyntax(fixed);

  // Fix 5: Fix sequence diagram syntax
  fixed = fixSequenceDiagramSyntax(fixed);

  // Fix 6: Fix pie chart syntax
  fixed = fixPieChartSyntax(fixed);

  // Fix 7: Fix state diagram syntax
  fixed = fixStateDiagramSyntax(fixed);

  // Fix 8: Fix journey diagram syntax
  fixed = fixJourneySyntax(fixed);

  // Fix 9: Fix gitgraph syntax
  fixed = fixGitGraphSyntax(fixed);

  // Fix 10: Fix requirement diagram syntax
  fixed = fixRequirementSyntax(fixed);

  return fixed;
}

/**
 * Fix multiple classes on same line
 * e.g., "class A,B,C;" -> "class A\nclass B\nclass C"
 */
function fixMultipleClassesOnLine(fixed: string): string {
  // Match patterns like "class A,B,C;" or "class A,B, C process;"
  const classMultiRegex = /class\s+([A-Za-z0-9_\-\s,]+)(?:\s+(\w+))?;/g;

  return fixed.replace(classMultiRegex, (match: string, classes: string, style: string) => {
    // Split by comma
    const classList = classes.split(',').map((c: string) => c.trim()).filter((c: string) => c);

    if (classList.length <= 1) {
      return match; // Only one class, no need to fix
    }

    // Create separate class definitions
    const results: string[] = [];
    for (const className of classList) {
      if (style) {
        results.push(`class ${className} ${style};`);
      } else {
        results.push(`class ${className};`);
      }
    }

    return results.join('\n');
  });
}

/**
 * Fix spacing between classDef and class statements
 */
function fixClassDefSpacing(fixed: string): string {
  // Add newline after classDef if followed by class on same line
  const classDefRegex = /(classDef\s+\w+\s*\{[^}]*\})\s*(class\s+)/g;
  return fixed.replace(classDefRegex, '$1\n$2');
}

/**
 * Fix extra semicolons in class definitions
 */
function fixClassSemicolons(fixed: string): string {
  // Remove trailing semicolons before classDef
  fixed = fixed.replace(/;\s*classDef/g, '\nclassDef');

  // Fix double semicolons
  fixed = fixed.replace(/;;/g, ';');

  return fixed;
}

/**
 * Fix common flowchart syntax issues
 */
function fixFlowchartSyntax(fixed: string): string {
  // Fix missing arrow direction (add default direction)
  const flowchartStart = fixed.match(/^flowchart\s+/m);
  if (flowchartStart) {
    // Ensure direction is specified
    if (!fixed.match(/flowchart\s+(TD|TB|BT|RL|LR)/)) {
      fixed = fixed.replace(/flowchart\s+/, 'flowchart TD ');
    }
  }

  // Fix node definitions without proper format
  // Add missing brackets around node IDs
  fixed = fixed.replace(/([A-Za-z0-9_\-]+)\[/g, '$1[');
  fixed = fixed.replace(/\](?=\s*-->|\s*--|\s*=>)/g, ']');

  // Fix edge labels without quotes
  fixed = fixed.replace(/--\s*([A-Za-z0-9_\-\s]+)\s*-->/g, '--"$1"-->');
  fixed = fixed.replace(/-->\s*([A-Za-z0-9_\-\s]+)\s*-->/g, '--> "$1" -->');

  // Fix incomplete edges
  fixed = fixed.replace(/--\s*$/gm, '-->');

  return fixed;
}

/**
 * Fix sequence diagram syntax
 */
function fixSequenceDiagramSyntax(fixed: string): string {
  // Fix missing participant declarations
  const participants = new Set<string>();
  const participantRegex = /(?:actor|participant|participant\s+as)\s+([A-Za-z0-9_\-]+)/gi;
  let match;
  while ((match = participantRegex.exec(fixed)) !== null) {
    participants.add(match[1]);
  }

  // Add missing participants before first use
  const lines = fixed.split('\n');
  const newLines: string[] = [];
  const addedParticipants = new Set<string>();

  for (const line of lines) {
    // Check if line references a participant
    const refMatch = line.match(/(?:actor|participant|->|--|>|<)\s+([A-Za-z0-9_\-]+)/i);
    if (refMatch && !participants.has(refMatch[1]) && !addedParticipants.has(refMatch[1])) {
      newLines.push(`participant ${refMatch[1]}`);
      addedParticipants.add(refMatch[1]);
    }
    newLines.push(line);
  }

  fixed = newLines.join('\n');

  // Fix missing colons in deactivate
  fixed = fixed.replace(/deactivate\s+([A-Za-z0-9_\-]+)(?!\s*;)/gi, 'deactivate $1:');

  return fixed;
}

/**
 * Fix pie chart syntax
 */
function fixPieChartSyntax(fixed: string): string {
  // Ensure pie chart starts with "pie"
  if (fixed.includes('pie')) {
    fixed = fixed.replace(/^title\s+/m, 'pie title ');
  }

  // Fix data values without quotes
  fixed = fixed.replace(/"?\s*:\s*(\d+\.?\d*)"?/g, ': $1');

  return fixed;
}

/**
 * Fix state diagram syntax
 */
function fixStateDiagramSyntax(fixed: string): string {
  // Fix state definitions without proper format
  fixed = fixed.replace(/^state\s+([A-Za-z0-9_\-]+)\s*$/gm, 'state $1');

  // Fix transition without arrow
  fixed = fixed.replace(/([A-Za-z0-9_\-]+)\s+([A-Za-z0-9_\-]+)\s*$/gm, '$1 --> $2');

  return fixed;
}

/**
 * Fix journey diagram syntax
 */
function fixJourneySyntax(fixed: string): string {
  // Fix section syntax
  fixed = fixed.replace(/^section\s+([A-Za-z0-9_\-\s]+)$/gm, 'section $1');

  // Fix task syntax
  fixed = fixed.replace(/task\s+"([^"]+)"\s*:\s*([A-Za-z0-9_\-]+)/g, 'task "$1": $2');

  return fixed;
}

/**
 * Fix gitgraph syntax
 */
function fixGitGraphSyntax(fixed: string): string {
  // Fix branch syntax
  fixed = fixed.replace(/branch\s+([A-Za-z0-9_\-]+)\s*$/gm, 'branch $1');

  // Fix commit syntax
  fixed = fixed.replace(/commit\s*$/gm, 'commit');

  return fixed;
}

/**
 * Fix requirement diagram syntax
 */
function fixRequirementSyntax(fixed: string): string {
  // Fix requirement syntax
  fixed = fixed.replace(/requirement\s+"([^"]+)"\s*\{/g, 'requirement "$1" {');

  // Fix element syntax
  fixed = fixed.replace(/element\s+"([^"]+)"\s*\{/g, 'element "$1" {');

  return fixed;
}

/**
 * Validate and return fixed Mermaid code with error info
 */
export function validateAndFixMermaid(code: string): {
  fixed: string;
  wasFixed: boolean;
  originalError?: string;
} {
  const original = code;
  const fixed = fixMermaidSyntax(code);

  return {
    fixed,
    wasFixed: fixed !== original,
  };
}